# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0002_remove_goodsinfo_gadv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gpic',
            field=models.ImageField(upload_to='static/df_goods'),
        ),
    ]
